name = "Ruby"
version = "0.1.0"
keywords = ["math", "hardware"]
defaultTargets = ["Ruby", "Toggler", "Adder", "Subtractor", "Comparator", "Mux", "TwoSorter", "BatchersBitonicMerger", "Decoder"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
autoImplicit = true
relaxedAutoImplicit = false
maxSynthPendingDepth = 3
grind.warning = false
maxRecDepth = 1000000

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.24.0"

[[lean_lib]]
name = "Ruby"

[[lean_lib]]
name = "Toggler"

[[lean_lib]]
name = "Adder"

[[lean_lib]]
name = "Subtractor"

[[lean_lib]]
name = "Comparator"

[[lean_lib]]
name = "Mux"

[[lean_lib]]
name = "TwoSorter"

[[lean_lib]]
name = "BatchersBitonicMerger"

[[lean_lib]]
name = "Decoder"
